### ISSUE TITLE
Move use of async out of feedmerger

### ISSUE THREAD

**Issue by pkra** [boolesrings/boolesrings-frontpage#1]
Otherwise, multiple calls to feedmergers can block each other.

We can do the async work in app.js just as well.

**Comment by scoskey** [comment]
Don't we need async in both?

**Comment by pkra** [comment]
Hm. I don't see why. Right now I'm thinking: feedmerger.js should just do "many feeds in => one feedobject out" (no feed as such). I don't want to write out the new feed (xml) within feedmerger anymore because we will use the resulting feedobject in app.js for both writing out a feed and writing out the page. Am I making sense?

**Comment by scoskey** [comment]
Well we want to gather the feeds asynchronously I mean

**Comment by pkra** [comment]
Ah. I thought you mean "using the async module" to synchronize :-) -- sorry about that.

Yes, I would gather both sets of feed asynchronously. But for building the page we need to wait until they finish (and sorted). I suppose we could just set up callbacks (or use promises :-) -- new research project!)

**Comment by scoskey** [comment]
Got it.
Maybe we could do forcing with side conditions.

**Comment by pkra** [comment]
That actually made me laugh out loud.

**Comment by pkra** [comment]
Fore future reference. https://github.com/jakearchibald/es6-promise (or rsvp or a+promises but this one is a pure ES6 implementation; but also corejs from babel might be nice if we want to explore ES6 long term)

**Comment by pkra** [comment]
https://github.com/zloirock/core-js#ecmascript-6-promises (that's corejs).

I think I've learned something tonight but no usable output. Are you ok with moving to promises via corejs? That looks promising to me.

**Comment by scoskey** [comment]
Ha. I don't quite get it, but it looks decent to me.

**Comment by pkra** [comment]
I couldn't figure out how to write an asynchronously-working module. But perhaps I should first figure out how to make the existing code work -- the call to feedmerger in app.js returns immediately right now (just try to log out the Feed object in app.js instead of in the async.each of feedmerger)

**Comment by pkra** [comment]
Argh. I messed too much with re-writing the git history. Anyway, this has been fixed in https://github.com/boolesrings/boolesrings-frontpage/commit/b51af948c367d8152f9f70cf9f0ab6df48d98f98 -- @scoskey was right, it needed to be in both.
